config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",registrations: 'users/registrations'
  }

  get  '/auth/:provider/callback', to: "items#new"
  root 'items#index'



  get 'purchase/index'
  get 'purchase/done'
  # devise_for :users, controllers: {registrations: 'users/registrations',sessions: 'users/sessions' }



  resources :addresses, only: [:new,:create]

  resources :card, only: [:new, :show, :create, :edit] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#destroy'
    end
  end
  resources :purchase, only: [:index] do
    collection do
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
    member do
      get 'index', to: 'purchase#index'
    end
  end

  resources :images 
  
  resources :items do
    collection do
      get 'sell'
    end

    member do
      get 'buy'
      post 'buy_create'
    end
  end

  resources :users,only:[:index, :destroy, :create, :edit, :show, :new] do
    collection do
      get 'result'
    end

    member do
      get 'todo'
      get 'past'
    end
  end
end

app/views/shared/_breadcrumb.html.haml
.breadcrumbs
  = breadcrumbs pretext: "",separator: " &gt; ", class: "breadcrumbs-list"

app/views/shared/_btn.html.haml
=link_to sell_items_path do
  .sell-icon
    %li.sell-text 出品
    %i.fas.fa-camera

app/views/shared/_fooder.html.haml
.footer-img
  .container
    .footer-img__heading
      スマホでかんたんフリマアプリ
    .footer-img__heading
      今すぐ無料ダウンロード！
    .footer-img__icon-box
      = image_tag "logo_white.svg", width: "60px", height: "auto";
      = link_to "", "#", class: "footer-img__icon-box--apple", style: "display:inline-block;overflow:hidden;background:url(https://linkmaker.itunes.apple.com/en-gb/badge-lrg.svg?releaseDate=2012-05-31&kind=iossoftware&bubble=ios_apps) no-repeat;width:135px;height:40px;"
      = link_to '#', class: "footer-img__icon-box--google" do
        = image_tag 'https://play.google.com/intl/ja/badges/static/images/badges/en_badge_web_generic.png', alt: 'Google Play で手に入れよう', width: "auto", height: "60px"
%footer
  .container.footer
    %nav.footer-nav
      %ul.footer-nav__list
        %li.footer-nav__list--item メルカリについて
        %li.footer-nav__list--item 会社概要（運営会社）
        %li.footer-nav__list--item 採用情報
        %li.footer-nav__list--item プレスリリース
        %li.footer-nav__list--item 公式ブログ
        %li.footer-nav__list--item メルカリロゴ利用ガイドライン
        %li.footer-nav__list--item
          = icon 'fab', 'twitter', class: "sns-link"
          = icon 'fab', 'facebook', class: "sns-link"

      %ul.footer-nav__list
        %li.footer-nav__list--item ヘルプ＆ガイド
        %li.footer-nav__list--item メルカリガイド
        %li.footer-nav__list--item らくらくメルカリ便
        %li.footer-nav__list--item ゆうゆうメルカリ便
        %li.footer-nav__list--item 大型メルカリ便
        %li.footer-nav__list--item 車体取引ガイド
        %li.footer-nav__list--item メルカリあんしん・あんぜん宣言！
        %li.footer-nav__list--item 偽ブランド品撲滅への取り組み
        %li.footer-nav__list--item メルカリボックス

      %ul.footer-nav__list
        %li.footer-nav__list--item プライバシーと利用規約
        %li.footer-nav__list--item プライバシーポリシー
        %li.footer-nav__list--item メルカリ利用規約
        %li.footer-nav__list--item あんしんスマホサポート制度に関する利用特約
        %li.footer-nav__list--item コンプライアンスポリシー
      %ul.footer-nav__list.divid
        %li.footer-nav__list--item 個人データの安全管理に係る基本方針
        %li.footer-nav__list--item 特定商取引に関する表記
        %li.footer-nav__list--item 資金決済法に基づく表示
        %li.footer-nav__list--item 法令順守と犯罪抑止のために


      %ul.footer-nav__list
        %li.footer-nav__list--item 国
        %li.footer-nav__list--item 日本
        %li.footer-nav__list--item United States

    = image_tag "fmarket_logo_white.png", class: "footer__logo", width: "130px", height: "auto"
    .footer__copyright © 2019 Mercari

app/views/shared/_footer.html.haml
.footer-img
  .container
    .footer-img__heading
      スマホでかんたんフリマアプリ
    .footer-img__heading
      今すぐ無料ダウンロード！
    .footer-img__icon-box
      = image_tag "logo_white.svg", width: "60px", height: "auto";
      = link_to "", "#", class: "footer-img__icon-box--apple", style: "display:inline-block;overflow:hidden;background:url(https://linkmaker.itunes.apple.com/en-gb/badge-lrg.svg?releaseDate=2012-05-31&kind=iossoftware&bubble=ios_apps) no-repeat;width:135px;height:40px;"
      = link_to '#', class: "footer-img__icon-box--google" do
        = image_tag 'https://play.google.com/intl/ja/badges/static/images/badges/en_badge_web_generic.png', alt: 'Google Play で手に入れよう', width: "auto", height: "60px"
%footer
  .container.footer
    %nav.footer-nav
      %ul.footer-nav__list
        %li.footer-nav__list--item メルカリについて
        %li.footer-nav__list--item 会社概要（運営会社）
        %li.footer-nav__list--item 採用情報
        %li.footer-nav__list--item プレスリリース
        %li.footer-nav__list--item 公式ブログ
        %li.footer-nav__list--item メルカリロゴ利用ガイドライン
        %li.footer-nav__list--item
          = link_to "https://twitter.com/" do
            = icon 'fab', 'twitter', class: "sns-link"
          = link_to "https://ja-jp.facebook.com/" do
            = icon 'fab', 'facebook', class: "sns-link"

      %ul.footer-nav__list
        %li.footer-nav__list--item ヘルプ＆ガイド
        %li.footer-nav__list--item メルカリガイド
        %li.footer-nav__list--item らくらくメルカリ便
        %li.footer-nav__list--item ゆうゆうメルカリ便
        %li.footer-nav__list--item 大型メルカリ便
        %li.footer-nav__list--item 車体取引ガイド
        %li.footer-nav__list--item メルカリあんしん・あんぜん宣言！
        %li.footer-nav__list--item 偽ブランド品撲滅への取り組み
        %li.footer-nav__list--item メルカリボックス

      %ul.footer-nav__list
        %li.footer-nav__list--item プライバシーと利用規約
        %li.footer-nav__list--item プライバシーポリシー
        %li.footer-nav__list--item メルカリ利用規約
        %li.footer-nav__list--item あんしんスマホサポート制度に関する利用特約
        %li.footer-nav__list--item コンプライアンスポリシー
      %ul.footer-nav__list.divid
        %li.footer-nav__list--item 個人データの安全管理に係る基本方針
        %li.footer-nav__list--item 特定商取引に関する表記
        %li.footer-nav__list--item 資金決済法に基づく表示
        %li.footer-nav__list--item 法令順守と犯罪抑止のために


      %ul.footer-nav__list
        %li.footer-nav__list--item 国
        %li.footer-nav__list--item 日本
        %li.footer-nav__list--item United States

    = link_to root_path do
      = image_tag "fmarket_logo_white.png", class: "footer__logo", width: "130px", height: "auto"
    .footer__copyright © 2019 Mercari

app/views/shared/_haeder.html.haml
.top-top
  .top-content
    .header
      .header__top
        .header__top--logo
          %img{src: "/assets/fmarket_logo_red.svg"}
        .header__top--text
          %input.search-form__input{placeholder: "何をお探しですか？", type: "text", value: ""}
          %i.fa.fa-search
      .header__menu
        .header__menu-left
          %i.fas.fa-indent
          %li.header__menu-left--category メルカリについて
          %i.fas.fa-tag
          %li.header__menu-left--brand ブランドから探す
        .header__menu-right
          %i.far.fa-heart
          %li.header__menu-right--like いいね！一覧
          %i.far.fa-bell
          %li.header__menu-right--news お知らせ
          %i.fas.fa-check
          %li.header__menu-right--todo やることリスト
          %i.far.fa-user
          %li.header__menu-right--mypage マイページ


      .my-menu
        .my-menu__img
        .my-menu__name
          テスト
        .my-menu__status
          %sapn 評価: 0
          %span 出品数: 0
        %ul.my-menu__money
          %li.my-menu__list--item.money-list 売上金
          %li.my-menu__list--item.money-list ポイント
        %ul.my-menu__list
          %li.my-menu__list--item いいね！一覧
          %li.my-menu__list--item 出品した商品 - 出品中
          %li.my-menu__list--item 出品した商品 - 取引中
          %li.my-menu__list--item 出品した商品 - 売却済
          %li.my-menu__list--item 購入した商品 - 取引中
          %li.my-menu__list--item 購入した商品 - 過去の取引

.sell-icon
  %li.sell-text 出品
  %i.fas.fa-camera

app/views/shared/_header.html.haml
.index-top
  .container
    .header
      .header__top
        = link_to root_path, class:"header__top--logo" do
          = image_tag 'fmarket_logo_red.png'
        .header__top--text
          %input.search-form__input{placeholder: "何をお探しですか？", type: "text", value: ""}
          %i.fa.fa-search
      .header__menu
        .header__menu-left
          %li.header__menu-left--category
            %i.fas.fa-indent
            Fmarketについて
          %li.header__menu-left--brand
            %i.fas.fa-tag
            ブランドから探す
        -if user_signed_in?
          .header__menu-right
            = link_to todo_user_path(current_user.id), class: 'header__menu-right--link' do
              %li.header__menu-right--like
                %i.far.fa-heart
                いいね！一覧
            = link_to todo_user_path(current_user.id), class: 'header__menu-right--link' do
              %li.header__menu-right--news
                %i.far.fa-bell
                お知らせ
            = link_to todo_user_path(current_user.id), class: 'header__menu-right--link' do
              %li.header__menu-right--todo
                %i.fas.fa-check
                やることリスト
            = link_to users_path do
              %li.header__menu-right--mypage
                %i.far.fa-user
                マイページ
        -else
          .header__menu-right2
            = link_to new_user_path do
              .header__menu-right2--registration
                新規会員登録
            = link_to new_user_session_path do
              .header__menu-right2--login
                ログイン

      .my-menu
        .my-menu__img
          = image_tag 'マイページ背景.jpeg'
        .my-menu__name
          -if user_signed_in?
            #{current_user.name}
        .my-menu__status
          %sapn 評価: 0
          %span 出品数: 0
        %ul.my-menu__money
          %li.my-menu__list--item.money-list 売上金
          %li.my-menu__list--item.money-list ポイント
        %ul.my-menu__list
          %li.my-menu__list--item いいね！一覧
          %li.my-menu__list--item 出品した商品 - 出品中
          %li.my-menu__list--item 出品した商品 - 取引中
          %li.my-menu__list--item 出品した商品 - 売却済
          %li.my-menu__list--item 購入した商品 - 取引中
          %li.my-menu__list--item 購入した商品 - 過去の取引

app/views/shared/_item.html.haml
.content
  .product
    .product-tag
      商品一覧
    .product-list
      .product-list__list
        .product-wrapper
          .product-wrapper__heading
            .heading-text
              新着アイテム
            .heading-option
              もっと見る
              %i.fa.fa-angle-right
              
          .product-wrapper__item
            .content
              .iteme-1
                .item-1__image
                  = image_tag src="https://o.imgz.jp/fashionnews/105709/cwhi5n7qwwrabxq.jpg", size: "187x188" 
                  .item-1__image__price
                    ¥1,000
                %li.item-1__name スカート
            .content
              .iteme-1
                .item-1__image
                  = image_tag src="https://o.imgz.jp/fashionnews/105709/cwhi5n7qwwrabxq.jpg", size: "187x188" 
                  .item-1__image__price
                    ¥1,000
                .item-1__name
                  スカート
            .content
              .iteme-1
                .item-1__image
                  = image_tag src="https://o.imgz.jp/fashionnews/105709/cwhi5n7qwwrabxq.jpg", size: "187x188" 
                  .item-1__image__price
                    ¥1,000
                .item-1__name
                  スカート
            .content
              .iteme-1
                .item-1__image
                  = image_tag src="https://o.imgz.jp/fashionnews/105709/cwhi5n7qwwrabxq.jpg", size: "187x188" 
                  .item-1__image__price
                    ¥1,000
                .item-1__name
                  スカート
            .content
              .iteme-1
                .item-1__image
                  = image_tag src="https://o.imgz.jp/fashionnews/105709/cwhi5n7qwwrabxq.jpg", size: "187x188" 
                  .item-1__image__price
                    ¥1,000
                .item-1__name
                  スカート
            .content
              .iteme-1
                .item-1__image
                  = image_tag src="https://o.imgz.jp/fashionnews/105709/cwhi5n7qwwrabxq.jpg", size: "187x188" 
                  .item-1__image__price
                    ¥1,000
                .item-1__name
                  スカート
            .content
              .iteme-1
                .item-1__image
                  = image_tag src="https://o.imgz.jp/fashionnews/105709/cwhi5n7qwwrabxq.jpg", size: "187x188" 
                  .item-1__image__price
                    ¥1,000
                .item-1__name
                  スカート
            .content
              .iteme-1
                .item-1__image
                  = image_tag src="https://o.imgz.jp/fashionnews/105709/cwhi5n7qwwrabxq.jpg", size: "187x188" 
                  .item-1__image__price
                    ¥1,000
                .item-1__name
                  スカート
            .content
              .iteme-1
                .item-1__image
                  = image_tag src="https://o.imgz.jp/fashionnews/105709/cwhi5n7qwwrabxq.jpg", size: "187x188" 
                  .item-1__image__price
                    ¥1,000
                .item-1__name
                  スカート
            .content
              .iteme-1
                .item-1__image
                  = image_tag src="https://o.imgz.jp/fashionnews/105709/cwhi5n7qwwrabxq.jpg", size: "187x188" 
                  .item-1__image__price
                    ¥1,000
                .item-1__name
                  スカート

app/views/shared/_items.html.haml
.product
  .container
    %h2.product__heading
      商品一覧
    %ul.product__tag-wrap
      %li レディース
      %li メンズ
      %li 家電・スマホ・カメラ
      %li おもちゃ・ホビー・グッズ


.product-list
  .container
    .product-list__inner
      .product-list__inner--heading
        %h3 新着アイテム
        .see-more
          もっと見る
          %i.fa.fa-angle-right

      .item-list
        - @items.each do |item|

          =link_to item_path(item.id),class:"item-list__card" do
            .item-list__card--img
              - @images = item.images
              - image = @images[0]
              = image_tag image.image.url, size: "187x187"
              - @sold = Buyer.find_by(item_id: item)
              - unless @sold == nil
                .sold-mark-wrap1
                  .sold-mark1
                    .sold-mark1__text1
                      SOLD
              .item-1__image__price
                ¥
                = item.price
            %li.item-1__name
              = item.name

app/views/shared/_op-shutter.html.haml
.overlay
  .animation-box
    = image_tag 'logo_red', class: "logo-animation"
    .animation-box__title
      .border-top
      .border-bottom
      .p-wrap
        %p.topToBottom f
        %p.bottomToTop r
        %p.topToBottom e
        %p.bottomToTop e
        %p.topToBottom m
        %p.bottomToTop a
        %p.topToBottom r
        %p.bottomToTop k
        %p.topToBottom e
        %p.bottomToTop t

app/views/shared/_side-bar.html.haml
.sidebar
  %ul.sidebar__top
    = link_to users_path do
      %li.sidebar__top--item
        マイページ
        %i.fas.fa-chevron-right
    =link_to todo_user_path(current_user.id) do
      %li.sidebar__top--item
        お知らせ
        %i.fas.fa-chevron-right
    =link_to todo_user_path(current_user.id) do
      %li.sidebar__top--item
        やることリスト
        %i.fas.fa-chevron-right
    %li.sidebar__top--item
      いいね！一覧
      %i.fas.fa-chevron-right
    = link_to sell_items_path do
      %li.sidebar__top--item
        出品する
        %i.fas.fa-chevron-right
    %li.sidebar__top--item
      出品した商品-出品中
      %i.fas.fa-chevron-right
    %li.sidebar__top--item
      出品した商品-取引中
      %i.fas.fa-chevron-right
    %li.sidebar__top--item
      出品した商品-売却済み
      %i.fas.fa-chevron-right
    =link_to past_user_path(current_user.id) do
      %li.sidebar__top--item
        購入した商品-取引中
        %i.fas.fa-chevron-right
    =link_to past_user_path(current_user.id) do
      %li.sidebar__top--item
        購入した商品-過去の取引
        %i.fas.fa-chevron-right
    %li.sidebar__top--item
      ニュース一覧
      %i.fas.fa-chevron-right
    %li.sidebar__top--item
      評価一覧
      %i.fas.fa-chevron-right
    %li.sidebar__top--item
      ガイド
      %i.fas.fa-chevron-right
    %li.sidebar__top--item
      お問い合わせ
      %i.fas.fa-chevron-right
  %ul.sidebar__middle
    %li.sidebar__middle--item
      プリペイ
    %li.sidebar__top--item
      売上・振込申請
      %i.fas.fa-chevron-right
    %li.sidebar__top--item
      ポイント
      %i.fas.fa-chevron-right
  %ul.sidebar__bottom
    %li.sidebar__bottom--item
      設定
    = link_to user_path(current_user.id) do
      %li.sidebar__top--item
        プロフィール
        %i.fas.fa-chevron-right
    %li.sidebar__top--item
      発送元・お届け先住所住所変更
      %i.fas.fa-chevron-right
    = link_to edit_card_path(current_user.id) do
      %li.sidebar__top--item
        支払い方法
        %i.fas.fa-chevron-right
    %li.sidebar__top--item
      メール/パスワード
      %i.fas.fa-chevron-right
    = link_to edit_user_path(current_user.id)do
      %li.sidebar__top--item
        本人情報
        %i.fas.fa-chevron-right
    %li.sidebar__top--item
      電話番号の確認
      %i.fas.fa-chevron-right
    =link_to "/users/:id",method: :delete,class:"" do
      %li.sidebar__top--item
        ログアウト
        %i.fas.fa-chevron-right

app/views/shared/_slider.html.haml
.slider
  .slider__item
    = link_to '#' do
      = image_tag 'top1.png', class: "slider__item--img"
    %h2
      スマホで かんたん
      %br
      フリマアプリ
    %p
      Fmarketはスマホカメラからすぐに出品できる
      %br
      購入時も安心な独自システムのアプリです
    .slider__store-link
      = link_to '#', class: "slider__store-link--apple" do
        = image_tag 'https://linkmaker.itunes.apple.com/en-gb/badge-lrg.svg?releaseDate=2012-05-31&kind=iossoftware&bubble=ios_apps',alt: 'Apple Store', width: "auto", height: "47px"

      = link_to '#', class: "slider__store-link--google" do
        = image_tag 'https://play.google.com/intl/ja/badges/static/images/badges/en_badge_web_generic.png',alt: 'Google Play で手に入れよう', width: "auto", height: "70px"

  .slider__item
    = link_to '#' do
      = image_tag 'top2.png', class: ".slider__item--img"

app/views/shared/＿breadcrumb.html.haml
.breadcrumb
  .breadcrumb__