config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",registrations: 'users/registrations'
  }

  get  '/auth/:provider/callback', to: "items#new"
  root 'items#index'



  get 'purchase/index'
  get 'purchase/done'
  # devise_for :users, controllers: {registrations: 'users/registrations',sessions: 'users/sessions' }



  resources :addresses, only: [:new,:create]

  resources :card, only: [:new, :show, :create, :edit] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#destroy'
    end
  end
  resources :purchase, only: [:index] do
    collection do
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
    member do
      get 'index', to: 'purchase#index'
    end
  end

  resources :images 
  
  resources :items do
    collection do
      get 'sell'
    end

    member do
      get 'buy'
      post 'buy_create'
    end
  end

  resources :users,only:[:index, :destroy, :create, :edit, :show, :new] do
    collection do
      get 'result'
    end

    member do
      get 'todo'
      get 'past'
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to :user
  has_many :images, dependent: :delete_all
  has_one :buyer
  has_one :seller

  accepts_nested_attributes_for :images
  accepts_nested_attributes_for :buyer
  accepts_nested_attributes_for :seller
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def new
  end

  def index

    @items = Item.all.includes(:images).order(created_at:"desc").limit(10)
    
  end

  def edit
    @item = Item.find(params[:id])
    @images = @item.images
  end

  def buy
    @card = Card.where(user_id: current_user.id).first
    unless @card ==nil
      @user = @card.user_id
      Payjp.api_key = 'sk_test_6c130d285ae2b7dd291fc04f'
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    @buyer = Buyer.new
    @seller = Seller.new
    @items = Item.all
    @item = Item.find(params[:id])
    @images = Image.all
  end

  def buy_create
    @item = Item.find(params[:id])
    @buyer = Buyer.new(buyer_params)
    @buyer.save!
    @seller = Seller.new(seller_params)
    @seller.save!
    if @buyer.save && @seller.save
      @card = Card.where(user_id: current_user.id).first
      Payjp.api_key = 'sk_test_6c130d285ae2b7dd291fc04f'
      Payjp::Charge.create(
      amount: @item.price, #支払金額を入力（itemテーブル等に紐づけても良い）
      customer: @card.customer_id, #顧客ID
      currency: 'jpy' #日本円
    )
    redirect_to root_path
    else
      render :buy
    end

  end

  def show
    unless user_signed_in?
      redirect_to new_user_path
    end
    @image = Image.where(params[:id])
    @items = Item.all.order(created_at:"desc").limit(6)
    # @images = Image.all.order(created_at:"desc").limit(6)
    @item = Item.find(params[:id])
    @sold = Buyer.find_by(item_id: @item.id)
    @prefecture = Prefecture.find(@item.area)
  end

  def sell
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    @item = Item.new
    @item.images.build
  end

  def update
    @item  = Item.find(params[:id])
    @item.update(item_params)
    params[:images][:image].each do |image|
      @item.images.create!(image: image, item_id: @item.id)
    end
    redirect_to root_path
  end

  def create
    @item  = Item.new(item_params)
    if @item.save
      params[:images][:image].each do |image|
        @item.images.create!(image: image, item_id: @item.id)
      end
      redirect_to root_path
    else
      redirect_to sell_items_path
    end
  end

  def destroy
    @item  = Item.find(params[:id])
    @item.destroy
    redirect_to root_path
  end


  # source ~/.zshrc
  def item_params
    params.require(:item).permit(:name, :description, :category, :status, :price, :burden, :area, :days, :user_id)
  end
  private

    def buyer_params
      params.require(:buyer).permit(:user_id, :item_id)
    end

    def seller_params
      params.require(:seller).permit(:user_id, :item_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/buy.html.haml
.wapper1
  .log
    .log__main
      =link_to root_path,class:"" do
        = image_tag 'fmarket_logo_red.svg', height: '49', width: '185'
  .buy-page
    .buy-page__top
      購入内容の確認
    .buy-page__center
      .buy-page__center--into
        .left
          - @images = @item.images
          - image = @images[0]
          = image_tag image.image.url, size: "80x80"
        .right
          .name
            =@item.name
          .plice
            ¥
            =@item.price
            (税込）着払い
    .buy-page__bottom
      .buy-page__bottom--into
        .top
          .plice
            .left
              支払い金額
            .right
              ¥
              =@item.price
          .buy-page__bottom--point
            %input{checked: "checked", class: "check", type: "checkbox"}
            ポイントを使用 (所持ポイント: P0)
        .middol
          .card
            .card__left
              支払い方法
            =link_to "",class:"card__right" do
              変更する
          .center
            = "**** **** **** " + @default_card_information.last4
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            %li.credit-limit
            = exp_month + " / " + exp_year
            %li visa
        .bottom
          .addres
            .addres__left
              支払い方法
            =link_to new_address_path,class:"addres__right" do
              変更する
          .news
            = current_user.address.postal_code
          .xx
            = current_user.address.prefucture
            = current_user.address.city
            = current_user.address.city_address
          .yy
            %li 　　　
            = current_user.address.name
            = current_user.address.name2
      = form_with url: buy_create_item_path(@item) ,method: :post, local: true do |f|
        %input{name: "buyer[user_id]", type: "hidden", value: current_user.id}
        %input{name: "buyer[item_id]", type: "hidden", value: @item.id}
        = f.fields_for @seller do |u|
          %input{name: "seller[user_id]", type: "hidden", value: @item.user_id}
          %input{name: "seller[item_id]", type: "hidden", value: @item.id}
        = f.submit '購入する', class: "buy-btn"
  .buy-footer
    .buy-footer__top
      =link_to "",class:"buy-footer__top--1" do
        プライバシーポリシー
      =link_to "",class:"buy-footer__top--2" do
        メルカリ利用規約
      =link_to "",class:"buy-footer__top--3" do
        特定商取引に関する表記
    .buy-footer__img
      = image_tag 'logo_gray.svg', height: '65', width: '80'
    .buy-footer__fin
      © Mercari, Inc.

app/views/items/edit.html.haml
.sell-wrap
  .container
    = link_to root_path do
      = image_tag '/assets/fmarket_logo_red.svg', class: "sell-wrap__logo"
    = form_with(model: @item, local: true) do |f|
      .sell-box
        %h2 商品の情報を入力
        .sell-box__img.sell-box__section
          %h3
            出品画像
            %span 必須
          %p 最大10枚までアップロードできます
          .drop-zone
            - @images.each do |image|
              .preview-box
                .preview-box__img-box
                  = image_tag image.image.url
                .preview-box__select
                  .preview-box__select--edit
                    %p 編集
                  .preview-box__select--delete
                    %p 削除
            %label.sell-box__img--input
              %p
                ドラッグアンドドロップ
                %br
                またはクリックしてファイルをアップロード
                = f.fields_for :images do |i|
                  = i.file_field :image, multiple: true, id: "sell-img", name: "images[image][]"


        .sell-box__info.sell-box__section
          %h3
            商品名
            %span 必須
          = f.text_field :name, class:"sell-box__info--input sell-box__info--name", placeholder: "商品名（必須40文字まで）"
          %h3.sell-box__info--textarea
            商品の説明
            %span 必須
          = f.text_area :description, class:"sell-box__info--input sell-box__info--description", rows: 6, placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"

        .sell-box__details.sell-box__section.sell-box__section2
          .sell-box__details--left
            %h3.text-gray 商品の詳細
          .sell-box__details--right
            %h4
              カテゴリー
              %span 必須
            .select-wrap
              = f.select :category, ["レディース", "メンズ"], class: "details", prompt: "---"
              = icon 'fas', 'chevron-down'
            %h4
              商品の状態
              %span 必須
            .select-wrap
              = f.select :status, ["新品、未使用", "未使用に近い"], class: "details", prompt: "---"
              = icon 'fas', 'chevron-down'

        .sell-box__delivery.sell-box__section.sell-box__section2
          .sell-box__delivery--left
            %h3.text-gray 配送について
          .sell-box__delivery--right
            %h4
              配送料の負担
              %span 必須
            .select-wrap
              = f.select :burden, ["送料込み(出品者負担)", "着払い(購入者負担)"], class: "details", prompt: "---"
              = icon 'fas', 'chevron-down'
            %h4
              発送元の地域
              %span 必須
            .select-wrap
              = f.collection_select :area, Prefecture.all, :id, :name, prompt: "---"
              = icon 'fas', 'chevron-down'
            %h4
              発送までの日数
              %span 必須
            .select-wrap
              = f.select :days, ["1〜2日で発送", "2〜3日で発送", "4〜7日で発送"], class: "details", prompt: "---"
              = icon 'fas', 'chevron-down'

        .sell-box__price.sell-box__section.sell-box__section2
          .sell-box__price--left
            %h3.text-gray 販売価格(300〜9,999,99
          .sell-box__price--right
            .price-flex
              %h4
                価格
                %span 必須
              = f.number_field :price, class:"price-flex__input", placeholder: "例）300"
            .price-flex
              %p.fee 販売手数料（10%）
              %p.result-fee -
            .price-flex
              %p.profit 販売利益
              %p.result-profit -
        .sell-box__confirmation.sell-box__section
          %p 禁止されている出品、行為を必ずご確認ください。
          %p またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。
          %p また、出品をもちまして加盟店規約に同意したことになります。
          = f.hidden_field :user_id ,value:current_user.id
          = f.submit "出品する", class: "sell-box__confirmation--exhibit-btn"

          = link_to users_path do
            .sell-box__confirmation--back-btn
              もどる
      %ul.sell-other
        %li プライバシーポリシー
        %li メルカリ利用規約
        %li 特定商取引による表記
    = image_tag '/assets/logo_gray.svg', width: "80px", height: "auto", class: "sell-wrap__logo-bottom"
    %p.copyright &copy; Freemarket_sample_64a

app/views/items/index.html.haml
= render 'shared/header'
= render 'shared/btn'
= render 'shared/slider'
= render 'shared/items'
= render 'shared/footer'

- unless user_signed_in?
  = render 'shared/op-shutter'

app/views/items/new.html.haml
.sign-up-wapper
  .sign-up
    .sign-up__header
      %img{src: "/assets/fmarket_logo_red.svg"}
    .sign-up__middle
      .sign-up__middle--top
        新規会員登録
      .sign-up__middle--bottom
        %li.sign-up__middle--bottom-1
          %i.far.fa-envelope
          メールアドレスで登録
        %li.sign-up__middle--bottom-2
          %i.fab.fa-facebook-square
          Facebookで登録する
        %li.sign-up__middle--bottom-3
          %i.fab.fa-google
          googleで登録する
  .wapper1
    .buy-footer
      .buy-footer__top
        =link_to "",class:"buy-footer__top--1" do
          プライバシーポリシー
        =link_to "",class:"buy-footer__top--2" do
          メルカリ利用規約
        =link_to "",class:"buy-footer__top--3" do
          特定商取引に関する表記
      .buy-footer__img
        = image_tag '/assets/logo_gray.svg', height: '65', width: '80'
      .buy-footer__fin
        © Mercari, Inc.

app/views/items/sell.html.haml
.sell-wrap
  .container
    = link_to root_path do
      = image_tag '/assets/fmarket_logo_red.svg', class: "sell-wrap__logo"
    = form_with(model: Item, local: true) do |f|
      .sell-box
        %h2 商品の情報を入力
        .sell-box__img.sell-box__section
          %h3
            出品画像
            %span 必須
          %p 最大10枚までアップロードできます
          .drop-zone
            %label.sell-box__img--input
              %p
                ドラッグアンドドロップ
                %br
                またはクリックしてファイルをアップロード
                = f.fields_for :images do |i|
                  = i.file_field :image, multiple: true, id: "sell-img", name: "images[image][]"

        .sell-box__info.sell-box__section
          %h3
            商品名
            %span 必須
          = f.text_field :name, class:"sell-box__info--input sell-box__info--name", placeholder: "商品名（必須40文字まで）", value: ""
          %h3.sell-box__info--textarea
            商品の説明
            %span 必須
          = f.text_area :description, class:"sell-box__info--input sell-box__info--description", rows: 6, placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"

        .sell-box__details.sell-box__section.sell-box__section2
          .sell-box__details--left
            %h3.text-gray 商品の詳細
          .sell-box__details--right
            %h4
              カテゴリー
              %span 必須
            .select-wrap
              = f.select :category, ["レディース", "メンズ"], class: "details", prompt: "---"
              = icon 'fas', 'chevron-down'
            %h4
              商品の状態
              %span 必須
            .select-wrap
              = f.select :status, ["新品、未使用", "未使用に近い"], class: "details", prompt: "---"
              = icon 'fas', 'chevron-down'

        .sell-box__delivery.sell-box__section.sell-box__section2
          .sell-box__delivery--left
            %h3.text-gray 配送について
          .sell-box__delivery--right
            %h4
              配送料の負担
              %span 必須
            .select-wrap
              = f.select :burden, ["送料込み(出品者負担)", "着払い(購入者負担)"], class: "details", prompt: "---"
              = icon 'fas', 'chevron-down'
            %h4
              発送元の地域
              %span 必須
            .select-wrap
              = f.collection_select :area, Prefecture.all, :id, :name, prompt: "---"
              = icon 'fas', 'chevron-down'
            %h4
              発送までの日数
              %span 必須
            .select-wrap
              = f.select :days, ["1〜2日で発送", "2〜3日で発送", "4〜7日で発送"], class: "details", prompt: "---"
              = icon 'fas', 'chevron-down'

        .sell-box__price.sell-box__section.sell-box__section2
          .sell-box__price--left
            %h3.text-gray 販売価格(300〜9,999,99
          .sell-box__price--right
            .price-flex
              %h4
                価格
                %span 必須
              = f.number_field :price, class:"price-flex__input", placeholder: "例）300"
            .price-flex
              %p.fee 販売手数料（10%）
              %p.result-fee -
            .price-flex
              %p.profit 販売利益
              %p.result-profit -
        .sell-box__confirmation.sell-box__section
          %p 禁止されている出品、行為を必ずご確認ください。
          %p またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。
          %p また、出品をもちまして加盟店規約に同意したことになります。
          = f.hidden_field :user_id ,value:current_user.id
          = f.submit "出品する", class: "sell-box__confirmation--exhibit-btn"

          = link_to users_path do
            .sell-box__confirmation--back-btn
              もどる
      %ul.sell-other
        %li プライバシーポリシー
        %li メルカリ利用規約
        %li 特定商取引による表記
    = image_tag '/assets/logo_gray.svg', width: "80px", height: "auto", class: "sell-wrap__logo-bottom"
    %p.copyright &copy; Freemarket_sample_64a

app/views/items/show.html.haml
= render 'shared/header'
.wrapper3
  .showpage
    .pp
    .show-top
      .show-top__tittle
        =@item.name
      .show-top__news
        「#{@item.name}」 は、19回の取引実績を持つすタップさんから出品されました。Tシャツ/カットソー(半袖/袖なし)/メンズの商品で、東京都から2~3日で発送されます。
      .show-top__explain
        .show-top__explain--image
          %ul.imagemain
            - @image = Image.where(item_id: params[:id])
            - @image.each do |i|
              %li=image_tag i.image.url, class:"imagemain-a" ,size:'300x300'
          - unless @sold == nil
            .sold-mark-wrap
              .sold-mark
                .sold-mark__text
                  SOLD
          %ul.imagesab
            - @image = Image.where(item_id: params[:id])
            - @image.each do |i|
              %li=image_tag i.image.url, class:"imagesab-a none" ,size:'60x60'
        .show-top__explain--status
          .status-a
            .left
              出品者
            =link_to"",class:"right" do
              = @item.user.name
              .face
                %i.fas.fa-smile-beam
                19
                %i.fas.fa-meh
                0
                %i.fas.fa-tired
                0
          .status-b
            .left
              カテゴリー
            =link_to"",class:"right" do
              =@item.category
          .status-c
            .left
              ブランド
            .right

          .status-d
            .left
              商品のサイズ
            .right
              M
          .status-e
            .left
              商品の状態
            .right
              =@item.status
          .status-f
            .left
              配送料の負担
            .right
              =@item.burden
          .status-g
            .left
              配送の方法
            .right
              未定
          .status-h
            .left
              配送元地域
            =link_to"",class:"right" do
              = @prefecture.name
          .status-i
            .left
              発送日の目安
            .right
              =@item.days
      .show-top__plice
        .show-top__plice--nmuber
          ¥
          =@item.price
        .show-top__plice--tax
          (税込)
        .show-top__plice--send
          =@item.burden
    - if @sold != nil
      .show-top__buy-sold-btn
        売り切れました
    - elsif @item.user_id == current_user.id
      .show-top__buy--create
        =link_to edit_item_path(@item.id), class:"show-edit" do
          商品の編集
        or
        =link_to "",class:"show-stop" do
          出品を一旦停止する
        =link_to item_path,class:"show-destroy", method: "DELETE" do
          この商品を削除する
    - else
      =link_to buy_item_path ,class:"show-top__buy" do
        購入画面に進む
    .show-top__text
      =@item.description
    .show-top__bottom
      .show-top__bottom--iine
        %i.far.fa-heart
        .iine
          いいね!
        .iine-num
          3
      .top__bottom--report
        %i.fa.fa-flag
        .report-text
        不適切な商品の報告
      .top__bottom--rock
        %i.fa.fa-lock
        あんしん・あんぜんへの取り組み
    .aa
    .show-messages
      .messages-left
        =link_to "", class: "" do
          %i.fas.fa-user-circle
      .messages-right
        .message-name
          =link_to "", class: "message-name__link" do
            Hayama328
        .message
          .message__top
            はじめまして。送料込みですといくらでしょうか？お安くしていただけると助かります！
          .message__bottom
            .message__bottom--left
              %i.far.fa-clock
              .time
                227 日前
            .message__bottom--right
              %i.fa.fa-flag
    .message-send
      .message-send__caution
        相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
      %input{class:"message-form", type:"text_area"}
      =link_to "",class:"send-btn" do
        コメントする
    .bb
      .left
        %i.fas.fa-chevron-left
        =link_to "",class: "left__link" do
          スズキスポーツ ヘッドキャップ L
      .right
        =link_to "",class: "right__link" do
          【秋田木工】コートハンガー 中古
        %i.fas.fa-chevron-right

    .show-ad
      .show-ad__line
        =link_to"https://www.facebook.com/",class:"facebook" do
          %i.fab.fa-facebook-square
        =link_to"https://twitter.com/",class:"twitter" do
          %i.fab.fa-twitter
        =link_to"https://www.pinterest.com",class:"pinterest" do
          %i.fab.fa-pinterest
    .cc
      Tシャツ/カットソー(半袖/袖なし) （メンズ） その他の商品
    .bottom
      -@items.each do |item|
        =link_to item_path(item.id),class:"" do
          .bottom__item-contents
            .bottom__item-contents--image
              -# = image_tag @item.images.image,class:"" size: "220x220"
            .bottom__item-contents--name
              .name
                =item.name
              .menu
                .price
                  ¥
                  =item.price
                .iine
                  %i.far.fa-heart
                  6

    .dd
  = render 'shared/footer'