config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",registrations: 'users/registrations'
  }

  get  '/auth/:provider/callback', to: "items#new"
  root 'items#index'



  get 'purchase/index'
  get 'purchase/done'
  # devise_for :users, controllers: {registrations: 'users/registrations',sessions: 'users/sessions' }



  resources :addresses, only: [:new,:create]

  resources :card, only: [:new, :show, :create, :edit] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#destroy'
    end
  end
  resources :purchase, only: [:index] do
    collection do
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
    member do
      get 'index', to: 'purchase#index'
    end
  end

  resources :images 
  
  resources :items do
    collection do
      get 'sell'
    end

    member do
      get 'buy'
      post 'buy_create'
    end
  end

  resources :users,only:[:index, :destroy, :create, :edit, :show, :new] do
    collection do
      get 'result'
    end

    member do
      get 'todo'
      get 'past'
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  before_action :set_card, only: [:new, :destroy, :show, :edit]
  
  require "payjp"

  def edit
    unless @card ==nil
      @user = @card.user_id
      Payjp.api_key = 'sk_test_6c130d285ae2b7dd291fc04f'
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  def new
    if @card
      redirect_to action: "show" 
    end  
  end

  def pay 
    Payjp.api_key = 'sk_test_6c130d285ae2b7dd291fc04f'

    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      description: '登録テスト',
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to result_users_path
      else
        redirect_to action: "pay"
        
      end
    end
  end

  def destroy
    if @card.blank?
    else
      Payjp.api_key = 'sk_test_6c130d285ae2b7dd291fc04f'
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.destroy
    end
      redirect_to edit_card_path(current_user.id)
  end

  def show
    if @card.blank?

      redirect_to action: "new" 
    else
      
      Payjp.api_key = 'sk_test_6c130d285ae2b7dd291fc04f'
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  private

  def set_card
    @card = Card.where(user_id: current_user.id).first
  end

end

app/helpers/card_helper.rb
module CardHelper
end

app/views/card/edit.html.haml
= render 'shared/header'
.contents-credit
  .content
    .credit-wrapper
      = render 'shared/side-bar'
      .credit
        .credit-header
          支払い方法
        .credit-main
          .credit-detail
          
            -@card = Card.find_by(user_id: current_user.id)
              -unless @card == nil
              .credit-list
                クレジットカード一覧
              .credit-setting
                %li.card-logo 
                  VISA
                %li.credit-number
                = "**** **** **** " + @default_card_information.last4
                - exp_month = @default_card_information.exp_month.to_s
                - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                %li.credit-limit
                = exp_month + " / " + exp_year
                = form_tag(delete_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
                  %input{ type: "hidden", name: "card_id", value: "",class:"delet-btn" }
                    %button.delet-btn 削除する

            -@card = Card.find_by(user_id: current_user.id)
              -if @card == nil
              =link_to new_card_path,class: "credit-btn" do
                クレジットカードを追加する
          .about
            支払い方法について
            %i.fa.fa-angle-right
= render 'shared/footer'

app/views/card/new.html.haml
= form_tag(pay_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
  .card-wrapper
    = render "users/progress"
    .card-wrapper__innuner
      .card-top
        %h2 支払い方法
      .card-bottom
        .card-number
          %h2 
            カード番号
            %span 必須
          = text_field_tag "number", "", class: "card-number__input", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
          %ul.card-campny
            = image_tag 'カード.png'
        .date
          %h2 
            有効期限
            %span 必須
          .year-and-month
            .year-and-month__innuner
              %select#exp_month{name: "exp_month", type: "text"}
                %option{value: ""} --
                %option{value: "1"}01
                %option{value: "2"}02
                %option{value: "3"}03
                %option{value: "4"}04
                %option{value: "5"}05
                %option{value: "6"}06
                %option{value: "7"}07
                %option{value: "8"}08
                %option{value: "9"}09
                %option{value: "10"}10
                %option{value: "11"}11
                %option{value: "12"}12
              = icon 'fas', 'chevron-down'
              %h3 月
            .year-and-month__innuner
              %select#exp_year{name: "exp_year", type: "text"}
                %option{value: ""} --
                %option{value: "2019"}19
                %option{value: "2020"}20
                %option{value: "2021"}21
                %option{value: "2022"}22
                %option{value: "2023"}23
                %option{value: "2024"}24
                %option{value: "2025"}25
                %option{value: "2026"}26
                %option{value: "2027"}27
                %option{value: "2028"}28
                %option{value: "2029"}29
              = icon 'fas', 'chevron-down'
              %h3 年
        .security-code
          %h2 
            セキュリティーコード 
            %span 必須
          = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
          .pop
          %i.fa.fa-question-circle 
          %h4{class: "popup"}
            カード裏面の番号とは？
          #card_token
          = submit_tag "次へ進む", id: "token_submit", class:"next--btn"
    = render "users/footer"